### PR TITLE
Reintegrate dev/v0.8.2

### PR DESCRIPTION
**Pull request by jvansanten**
Major changes:

T2Worker:
- Added retry with backoff to handle processing t2s with dependencies in parallel
- Improved performance with replicated Mongo clusters

AbsCoreCommand
- Override config values with environment variables (e.g. for setting the Mongo URI)

JobCommand:
- Use BaseModel instances to parse job file
- Download input artifacts before executing tasks
- Allow go-template-style expressions in tasks (powered by `ExpressionParser`)
- Replace `multiplier` with `expand_with` to allow parallel task instances to be parameterised e.g. over a set of input files. Legacy job definitions with `multiplier` are still supported.
- Added ProcessCommand, for executing only a single task from a job definition, e.g. for parallel execution across nodes

AmpelDB:
- Read from secondaries of replica sets by default. This makes no difference for a standalone mongo, but improves `find()` and `aggregate()` performance (at the potential expense of consistency) in replicated clusters.

T3SimpleDataLoader:
- pymongo 4.1 compatibility

T2Command:
- use `one_db` for compatibility with `ampel job`

ConfigValidator:
- remove special case for process_name (runtime-supplied fields are marked `Traceless`)

CompilerOptions:
- reimplement as `AuxAliasableModel` to allow (validated) initialization from a name

T3DefaultBufferSupplier:
- gracefully handle empty result set

### CODE REVIEW

**Comment by vbrinnel** [comment]
T2Worker: ✔
AmpelDB: ✔
T3SimpleDataLoader: ✔
T3DefaultBufferSupplier: ✔
ConfigValidator: ✔
CompilerOptions: ✔
AbsCoreCommand: ✔ [Note: we should restrict this (and CLI overrides) in the future]

**Comment by vbrinnel** [comment]
T2Command: _use one_db for compatibility with ampel job_

This should be an option, similar to Ampel-plot/ampel-plot-cli/ampel/cli/PlotCommand.py:62 (with a better description). I can add that later.

**Comment by vbrinnel** [comment]
JobCommand:

**Use BaseModel instances to parse job file.**
Good, had this on my task list (Two side-remarks, I would prefer having the myriad of sub-models defined in their own file and  `@validators` be less used for future-proof reasons as the same effects can be obtained via classical/non-pydantic-specific ctors but that's just me being annoying) 

**Download input artifacts before executing tasks**
Don't know what that means, but I trust it's the right thing to do

**Allow go-template-style expressions in tasks (powered by ExpressionParser)**
Still unsure about that, but it can be refined later

**Replace multiplier with expand_with to allow parallel task instances to be parameterised e.g. over a set of input files**
Great addition, thx

**Added ProcessCommand, for executing only a single task from a job definition, e.g. for parallel execution across nodes**
How does this differ from the `-task #` from `JobCommand` ?

**Something else**
A worry I have with the proposed `JobCommand` update is that the schema saved into the DB is the one pre-morphing with unresolved expressions:

https://github.com/AmpelProject/Ampel-core/blob/215f437b6aa8fff9eb41295b44631cd3bad68d1b/ampel/cli/JobCommand.py#L294-L299

whereas in the current master, the schema saved into the DB is the "final" one, after transformations.

https://github.com/AmpelProject/Ampel-core/blob/71a5cbbb4ca30beff36abcb1dcdb9d350fabb638/ampel/cli/JobCommand.py#L267-L272

**Comment by jvansanten** [comment]
> T2Command: _use one_db for compatibility with ampel job_
> 
> This should be an option, similar to Ampel-plot/ampel-plot-cli/ampel/cli/PlotCommand.py:62 (with a better description). I can add that later.

Added in 15242791c4b0fa14043027a19ad73bfc8a29d5ba

**Review by vbrinnel — APPROVED** [review]
thx

**Pull request merged**
